apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  replicas: 1
  serviceName: postgres-statefulset 
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.0-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: POSTGRES_USER
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: POSTGRES_DB
          - name: POSTGRES_HOST_AUTH_METHOD
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: POSTGRES_HOST_AUTH_METHOD
        volumeMounts:
        - name: postgres-pvc
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-pvc
        persistentVolumeClaim:
          claimName: postgres-pvc

